sudo: false
language: c

install:
  - git clone --depth 1 https://github.com/sstephenson/bats.git

script:
  - PATH="./bats/bin:$PATH" test/run

notifications:
  slack:
    - secure: "XxU56x0OXPno1Pv4bzJ5UhJLYd4aetBTsiOMETuc/WtAnPmCvop1xel1ZcL/bxRC52MFKpmD/zv34GaJNC7QpoutQheHzclKL+ANqVtWgvjEtvMSroDv2NXvQz7Vkn4SmhvUF4c3pRXtgBE3wFDFI5bpHaPUtjx68UZ++BWcz4owDPVRM6H3BI5B6sGbY6Z8NhXtWO9HaaJ7jxbFkQNtSk/X/ts+X7AcuiQFxQLgRAk2KXyK7Ba6rDWue+bXFxwX7+3KzKozOToImPTUp1dM0ZsUSOPasClH0Vu2Zbd3DBchOKFFiICPhDX9FBjNCbvKnKey/FScdYJeuM8/9sZ538Z2K2Xh9SqhicG0LBBVKv2lpfHfefUxj7lbZR0H9AZOK9HrOjJxeC+Dwf4rmKVPu460rWJmLn6lsAcecQUx6iNwO4IzBN6dHYi1TxtDrQ8GYKzCFwRq0gDyiBgrWI0AUq3Hk4/kqC7rrX6hcRKpN8tGFqB1Bg/1jon6Ym7ad/Bcq7J4RkohzsPwAZ11kSFPTTDzJjGRJiIE39TTk6Sur+HZ687Qf9mmQa7UB62pKZ9RqRtSeTKtUXNNeNEQshPjdaY9bptp3pqpNcjJ/sAOY3xxk/MpgBnkmsZh8Lpv9TqSTnnzF0hH23r1N2J+AoI0WP4PFIeH170eDR++zo+xVfw="
